// packages/renderer/src/react/TegakiRenderer.tsx
'use client';

import { type ComponentProps, createElement, type ReactNode, type Ref, useEffect, useImperativeHandle, useRef } from 'react';
import { TegakiEngine, type TegakiEngineOptions } from '../core/engine.ts';
import type { Coercible } from '../lib/utils.ts';
import { coerceToString } from '../lib/utils.ts';
import type { TegakiEffects } from '../types.ts';

/** Imperative handle exposed via the `ref` prop. */
export interface TegakiRendererHandle {
  /** The underlying engine instance. `null` before mount and after unmount. */
  readonly engine: TegakiEngine | null;
  /** The container DOM element. */
  readonly element: HTMLDivElement | null;
}

export interface TegakiRendererProps<E extends TegakiEffects<E> = Record<string, never>>
  extends Omit<TegakiEngineOptions, 'effects'>,
    Omit<ComponentProps<'div'>, 'children' | 'ref'> {
  /** Imperative handle ref for playback controls and DOM access. */
  ref?: Ref<TegakiRendererHandle>;

  /** Children coerced to string. Strings and numbers are kept; everything else is ignored. */
  children?: Coercible;

  /** Visual effects applied during canvas rendering. */
  effects?: E;
}

function reactCreateElement(tag: string, props: Record<string, any>, ...children: (ReactNode | string)[]): ReactNode {
  return createElement(tag, { ...props, key: props['data-tegaki'] }, ...children);
}

export function TegakiRenderer<const E extends TegakiEffects<E> = Record<string, never>>({
  ref,
  font,
  text,
  children,
  time: timeProp,
  onComplete,
  effects,
  segmentSize,
  timing,
  showOverlay,
  ...divProps
}: TegakiRendererProps<E>) {
  const containerRef = useRef<HTMLDivElement>(null);
  const engineRef = useRef<TegakiEngine | null>(null);
  const resolvedText = text ?? coerceToString(children);

  // Render the element tree via the engine's static method (SSR-safe)
  const engineOptions: TegakiEngineOptions = {
    text: resolvedText,
    font,
    time: timeProp,
    effects: effects as Record<string, any>,
    segmentSize,
    timing,
    showOverlay,
    onComplete,
  };
  const { rootProps, content } = TegakiEngine.renderElements(engineOptions, reactCreateElement);
  const { style: rootStyle, ...rootAttrs } = rootProps;

  // Create engine on mount, adopting the pre-rendered elements
  useEffect(() => {
    const engine = new TegakiEngine(containerRef.current!, { adopt: true });
    engineRef.current = engine;
    return () => {
      engine.destroy();
      engineRef.current = null;
    };
  }, []);

  // Update engine with current props every render
  useEffect(() => {
    engineRef.current?.update(engineOptions);
  });

  // Imperative handle
  useImperativeHandle(
    ref,
    () => ({
      get engine() {
        return engineRef.current;
      },
      get element() {
        return containerRef.current;
      },
    }),
    [],
  );

  // Merge engine root styles with user-provided styles
  const mergedStyle = { ...rootStyle, ...divProps.style };

  return (
    <div ref={containerRef} {...rootAttrs} {...divProps} style={mergedStyle}>
      {content}
    </div>
  );
}

// packages/renderer/src/solid/TegakiRenderer.tsx
/** @jsxImportSource solid-js */
import { createEffect, createMemo, type JSX, on, onCleanup, onMount, splitProps } from 'solid-js';
import { TegakiEngine } from '../core/engine.ts';
import type { TegakiEngineOptions } from '../core/types.ts';
import type { TegakiEffects } from '../types.ts';

export interface TegakiRendererProps extends Omit<TegakiEngineOptions, 'effects'> {
  /** Visual effects applied during canvas rendering. */
  effects?: TegakiEffects<Record<string, any>>;
  class?: string;
  ref?: (handle: TegakiRendererHandle) => void;
  [key: string]: any;
}

export interface TegakiRendererHandle {
  readonly engine: TegakiEngine | null;
  readonly element: HTMLDivElement | null;
}

function solidCreateElement(tag: string, props: Record<string, any>, ...children: (JSX.Element | string)[]): JSX.Element {
  const parts: string[] = [];
  for (const [key, value] of Object.entries(props)) {
    if (value == null || value === false) continue;
    if (key === 'style' && typeof value === 'object') {
      const css = Object.entries(value)
        .filter(([, v]) => v != null)
        .map(([k, v]) => {
          const prop = k.startsWith('--') ? k : k.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);
          const val = typeof v === 'number' && !k.startsWith('--') ? `${v}px` : String(v);
          return `${prop}:${val}`;
        })
        .join(';');
      if (css) parts.push(`style="${escapeAttr(css)}"`);
    } else if (typeof value === 'boolean') {
      parts.push(key);
    } else {
      parts.push(`${key}="${escapeAttr(String(value))}"`);
    }
  }
  const open = parts.length > 0 ? `<${tag} ${parts.join(' ')}>` : `<${tag}>`;
  const content = children.map((c) => (typeof c === 'string' && !c.startsWith('<') ? escapeHtml(c) : (c as string))).join('');
  return `${open}${content}</${tag}>` as unknown as JSX.Element;
}

function escapeAttr(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

export function TegakiRenderer(props: TegakiRendererProps) {
  const [local, divProps] = splitProps(props, [
    'text',
    'font',
    'time',
    'onComplete',
    'effects',
    'segmentSize',
    'timing',
    'showOverlay',
    'direction',
    'ref',
  ]);

  let container!: HTMLDivElement;
  let engine: TegakiEngine | null = null;

  const engineOptions = createMemo<TegakiEngineOptions>(() => ({
    text: local.text,
    font: local.font,
    time: local.time,
    effects: local.effects as Record<string, any>,
    segmentSize: local.segmentSize,
    timing: local.timing,
    showOverlay: local.showOverlay,
    direction: local.direction,
    onComplete: local.onComplete,
  }));

  // Compute initial HTML once — after the engine adopts, all updates go through engine.update().
  const { rootProps, content } = TegakiEngine.renderElements(engineOptions(), solidCreateElement);
  const innerHTML = content as unknown as string;

  onMount(() => {
    engine = new TegakiEngine(container, { ...engineOptions(), adopt: true });
    local.ref?.({ engine, element: container });
  });

  onCleanup(() => {
    engine?.destroy();
    engine = null;
  });

  createEffect(
    on(engineOptions, (options) => {
      engine?.update(options);
    }),
  );

  const mergedStyle = { ...rootProps.style, ...(typeof divProps.style === 'object' ? divProps.style : {}) };

  return <div ref={container!} data-tegaki="root" {...divProps} style={mergedStyle} innerHTML={innerHTML} />;
}
